build:
  image: docker:20.10.12
  stage: build
  services:
    - name: docker:20.10.12-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    # When using dind service, you must instruct docker to talk with the
    # daemon started inside of the service. The daemon is available with
    # a network connection instead of the default /var/run/docker.sock socket.
    #
    # The 'docker' hostname is the alias of the service container as described at
    # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
    #
    # If you're using GitLab Runner 12.7 or earlier with the Kubernetes executor and Kubernetes 1.6 or earlier,
    # the variable must be set to tcp://localhost:2375 because of how the
    # Kubernetes executor connects services to the job container
    # DOCKER_HOST: tcp://localhost:2375
    #
    # using "docker" as the host is only possible if you alias the service
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2

    IMAGE_TAG: "${CI_REGISTRY_IMAGE}:latest"
  before_script:
    - docker logout
    - echo "${DOCKER_REGISTRY_PASS}" | docker login "${DOCKER_REGISTRY}" --username "${DOCKER_REGISTRY_USER}" --password-stdin
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
